# Generated by Django 5.1.7 on 2025-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_booking_caravailability_carfeature_carimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listerprofile',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='listerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
