# Generated by Django 5.1.7 on 2025-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_listerprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingoverview',
            name='renter_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.CharField(blank=True, choices=[('2+', '2+'), ('4+', '4+'), ('5+', '5+'), ('7+', '7+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='suitcases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Minivan', 'Minivan'), ('SUV', 'Suv'), ('SMALL CAR', 'Small Car'), ('Medium Car', 'Medium Car'), ('Pickup Truck', 'Pickup Truck'), ('Luxury', 'Luxury'), ('Van/Bus', 'Van/Bus'), ('Electric car', 'Electric car')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CarFeature',
        ),
    ]
