# Generated by Django 5.1.7 on 2025-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravailability',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
