# Generated by Django 5.1.7 on 2025-04-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_caravailability_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renterprofile',
            name='driving_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/'),
        ),
    ]
